### GET Books
GET http://localhost:5000/books
Accept: application/json

### GET single Book
GET http://localhost:5000/books/1
Accept: application/json

### POST Book
POST http://localhost:5000/books
Content-Type: application/json

{
  "isbn": "978-1098139872",
  "title": "Learning JavaScript Design Patterns: A JavaScript and React Developer's Guide",
  "author": "Addy Osmani",
  "description": "The web development landscape has changed dramatically. JavaScript has become one of the most popular programming languages in the world and is used for everything from simple scripts to complex web applications. The JavaScript language has evolved to include modules, promises, and async/await, which has heavily influenced how we architect applications. The way developers write components, such as with React, has also significantly impacted how they think about maintainability. This has resulted in the need for modern patterns that take these new changes into account."
}


### PATCH Book
PATCH http://localhost:5000/books/1
Content-Type: application/json

{
  "title": "Updated Book 150"
}

### DELETE Book
DELETE http://localhost:5000/books/12