### GET Books
GET http://localhost:5000/books
Accept: application/json

### GET single Book
GET http://localhost:5000/books/1
Accept: application/json

### POST Book
POST http://localhost:5000/books
Content-Type: application/json

{
  "isbn": "Test ISBN 25",
  "title": "New Book 25",
  "author": "New Author",
  "description": "1234567890"
}


### PATCH Book
PATCH http://localhost:5000/books/1
Content-Type: application/json

{
  "title": "Updated Book 50"
}

### DELETE Book
DELETE http://localhost:5000/books/9