### GET Page
GET http://localhost:5000/pages
Accept: application/json

### GET single Page
GET http://localhost:5000/pages/1
Accept: application/json

### POST Page
POST http://localhost:5000/pages
Content-Type: application/json

{
  "name": "New Page",
  "author": "New Author",
  "isbn": "1234567890"
}


### PATCH Page
PATCH http://localhost:5000/pages/1
Content-Type: application/json

{
  "name": "Updated Page",
  "author": "Updated Author",
  "isbn": "1234567890"
}

### DELETE Page
DELETE http://localhost:5000/pages/1